services:
  host_docker: # DB_HOST in .env should match the service name here
    image: mysql:8.0
    container_name: laravel-api-kit-db
    cpus: '2'
    mem_limit: '2g'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_aktbiz_ecommerce_3" # DB_DATABASE in .env should match this value
    ports:
      - "3306:3306" # The host port before colon separator should be put on DB_PORT at .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 30
      interval: 10s
      start_period: 60s
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-api-kit-app
    cpus: '2'
    mem_limit: '2g'
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      host_docker: # DB_HOST in .env should match the service name here
        condition: service_healthy
    networks:
      - laravel
    restart: unless-stopped

volumes:
  db_data:

networks:
  laravel:
    driver: bridge